# Generated by Django 3.2.3 on 2021-05-25 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_auto_20210525_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='views',
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.ManyToManyField(related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
