# Generated by Django 3.2.3 on 2021-06-03 00:50

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210525_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.book_cover_thumbnail),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.book_image_thumbnail),
        ),
    ]
