# Generated by Django 3.2.3 on 2021-06-03 01:07

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210603_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to=core.utils.book_cover_thumbnail),
        ),
    ]
