# Generated by Django 3.2.3 on 2021-06-03 02:30

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.book_cover_thumbnail),
        ),
    ]
