# Generated by Django 3.2.3 on 2021-06-08 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20210608_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookimage',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
