# Generated by Django 3.2.3 on 2021-06-09 19:17

import core.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20210608_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=core.utils.book_image_thumbnail),
        ),
    ]
