# Generated by Django 3.2.3 on 2021-06-10 18:24

import core.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_bookimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=core.utils.book_cover_thumbnail),
        ),
    ]
