# Generated by Django 3.2.3 on 2021-08-06 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='views',
        ),
    ]
