# Generated by Django 3.2.3 on 2021-08-12 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_remove_book_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.CreateModel(
            name='BookCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(blank=True, choices=[('Fiction', 'Fiction'), ('Nonfiction', 'Nonfiction'), ('Academic', 'Academic'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Religion and Spirituality', 'Religion and Spirituality'), ('Christianity', 'Christianity'), ('Islamic', 'Islamic'), ('Science Fiction', 'Science Fiction'), ('For Student', 'For Student'), ('Others', 'Others')], max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='books.book')),
            ],
        ),
    ]
