# Generated by Django 3.2.3 on 2021-08-12 14:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20210812_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Fiction', 'Fiction'), ('Nonfiction', 'Nonfiction'), ('Academic', 'Academic'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Religion and Spirituality', 'Religion and Spirituality'), ('Christianity', 'Christianity'), ('Islamic', 'Islamic'), ('Science Fiction', 'Science Fiction'), ('For Student', 'For Student'), ('Others', 'Others')], max_length=100), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='BookCategories',
        ),
    ]
