# Generated by Django 3.2.3 on 2021-08-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='categories',
        ),
    ]
