# Generated by Django 3.2.3 on 2021-09-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_auto_20210831_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='final_shipping_cost',
            field=models.FloatField(default=0),
        ),
    ]
