# Generated by Django 3.2.3 on 2021-09-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='book',
            new_name='cart_book',
        ),
    ]
