# Generated by Django 3.2.3 on 2021-09-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_rename_book_cart_cart_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_book',
        ),
        migrations.AddField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.book'),
            preserve_default=False,
        ),
    ]
