# Generated by Django 3.2.3 on 2021-09-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_alter_shippingnote_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
