# Generated by Django 3.2.3 on 2021-09-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_shippingaddress_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='estimated_shipping_cost',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='final_shipping_cost',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_shipping_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='final_shipping_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='on_board',
            field=models.BooleanField(default=False),
        ),
    ]
