# Generated by Django 3.2.3 on 2021-09-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0037_auto_20210913_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.shippingaddress'),
            preserve_default=False,
        ),
    ]
