# Generated by Django 3.2.3 on 2021-06-10 18:24

import core.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(default='profile_images/default_profile_pic.png', upload_to=core.utils.profile_image_thumbnail),
        ),
    ]
