# Generated by Django 3.2.3 on 2021-08-06 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_remove_book_views'),
        ('user', '0002_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.TextField(default=None)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='books.book')),
            ],
            options={
                'verbose_name': 'Book View',
            },
        ),
    ]
